id: P000549
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG869
  title: བོད་ལྗོངས་ཡུལ་སྐོར
  author: ''
  volumes:
    32b3280e79034ea38cd353b44114ae13:
      image_group_id: I1KG920
      title: Volume 1 of bod ljongs yul skor
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
